// Smart App - Demo Data for Development

import { SmartCollection, SmartDocument, SmartDocumentAnalysis, SmartChatMessage } from './types'

export const demoCollections: SmartCollection[] = [
  {
    id: 'col-1',
    user_id: 'demo-user-001',
    name: 'All Documents',
    description: 'Default collection for all documents',
    color: '#6366f1',
    icon: 'folder',
    is_default: true,
    document_count: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'col-2',
    user_id: 'demo-user-001',
    name: 'Palm Jumeirah Villas',
    description: 'Floor plans and specs for Palm Jumeirah properties',
    color: '#10b981',
    icon: 'home',
    is_default: false,
    document_count: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'col-3',
    user_id: 'demo-user-001',
    name: 'Downtown Apartments',
    description: 'Downtown Dubai property documents',
    color: '#f59e0b',
    icon: 'building',
    is_default: false,
    document_count: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'col-4',
    user_id: 'demo-user-001',
    name: 'Plot Comparisons',
    description: 'Land plots for comparison analysis',
    color: '#ef4444',
    icon: 'map',
    is_default: false,
    document_count: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const demoAnalysis: Record<string, SmartDocumentAnalysis> = {
  'doc-1': {
    id: 'analysis-1',
    document_id: 'doc-1',
    plot_size: 8500,
    built_up_area: 6200,
    bedroom_count: 5,
    bathroom_count: 6,
    floor_count: 2,
    parking_spaces: 3,
    room_dimensions: [
      { name: 'Master Bedroom', width: 18, length: 22, area: 396 },
      { name: 'Living Room', width: 25, length: 30, area: 750 },
      { name: 'Kitchen', width: 15, length: 20, area: 300 },
      { name: 'Bedroom 2', width: 14, length: 16, area: 224 },
      { name: 'Bedroom 3', width: 14, length: 15, area: 210 },
    ],
    balcony_area: 450,
    terrace_area: null,
    garden_area: 2200,
    pool_size: '12m x 6m',
    features: ['private_pool', 'maid_room', 'driver_room', 'home_cinema', 'gym', 'sauna'],
    extracted_text: null,
    summary: 'Luxurious 5-bedroom Garden Villa on Palm Jumeirah featuring 6,200 sqft built-up area on 8,500 sqft plot. Includes private pool, separate maid and driver quarters, home cinema, and gym. Prime location on Frond K with beach access.',
    extraction_confidence: 0.92,
    processed_at: new Date().toISOString(),
    processing_time_ms: 3500,
    model_used: 'gpt-4-vision',
  },
  'doc-2': {
    id: 'analysis-2',
    document_id: 'doc-2',
    plot_size: 15000,
    built_up_area: 12500,
    bedroom_count: 7,
    bathroom_count: 8,
    floor_count: 3,
    parking_spaces: 5,
    room_dimensions: [
      { name: 'Master Suite', width: 25, length: 30, area: 750 },
      { name: 'Grand Living', width: 35, length: 45, area: 1575 },
      { name: 'Dining Hall', width: 20, length: 25, area: 500 },
      { name: 'Kitchen', width: 18, length: 22, area: 396 },
    ],
    balcony_area: 800,
    terrace_area: 1200,
    garden_area: 4500,
    pool_size: '18m x 10m',
    features: ['infinity_pool', 'beach_access', 'private_marina', 'elevator', 'wine_cellar', 'spa', 'staff_quarters'],
    extracted_text: null,
    summary: 'Ultra-luxury 7-bedroom Signature Villa spanning 12,500 sqft on a 15,000 sqft beachfront plot. Features private marina, infinity pool, beach access, elevator, wine cellar, and full spa. Includes separate staff quarters.',
    extraction_confidence: 0.95,
    processed_at: new Date().toISOString(),
    processing_time_ms: 4200,
    model_used: 'gpt-4-vision',
  },
  'doc-3': {
    id: 'analysis-3',
    document_id: 'doc-3',
    plot_size: null,
    built_up_area: 1450,
    bedroom_count: 2,
    bathroom_count: 3,
    floor_count: 1,
    parking_spaces: 1,
    room_dimensions: [
      { name: 'Master Bedroom', width: 14, length: 16, area: 224 },
      { name: 'Living/Dining', width: 18, length: 24, area: 432 },
      { name: 'Second Bedroom', width: 12, length: 14, area: 168 },
    ],
    balcony_area: 180,
    terrace_area: null,
    garden_area: null,
    pool_size: null,
    features: ['burj_khalifa_view', 'balcony', 'built_in_wardrobes', 'premium_finishes'],
    extracted_text: null,
    summary: 'Premium 2-bedroom apartment in Burj Vista with stunning Burj Khalifa views. 1,450 sqft living space with spacious balcony. High-end finishes throughout with built-in wardrobes.',
    extraction_confidence: 0.89,
    processed_at: new Date().toISOString(),
    processing_time_ms: 2800,
    model_used: 'gpt-4-vision',
  },
  'doc-4': {
    id: 'analysis-4',
    document_id: 'doc-4',
    plot_size: 12000,
    built_up_area: null,
    bedroom_count: null,
    bathroom_count: null,
    floor_count: null,
    parking_spaces: null,
    room_dimensions: [],
    balcony_area: null,
    terrace_area: null,
    garden_area: 12000,
    pool_size: null,
    features: ['corner_plot', 'lagoon_view', 'premium_location', 'g_plus_2_allowance'],
    extracted_text: null,
    summary: 'Premium corner plot (12,000 sqft) in Harmony Phase 2 with direct lagoon views. G+2 building allowance. One of the most sought-after locations in Tilal Al Ghaf.',
    extraction_confidence: 0.94,
    processed_at: new Date().toISOString(),
    processing_time_ms: 2100,
    model_used: 'gpt-4-vision',
  },
  'doc-5': {
    id: 'analysis-5',
    document_id: 'doc-5',
    plot_size: 9500,
    built_up_area: null,
    bedroom_count: null,
    bathroom_count: null,
    floor_count: null,
    parking_spaces: null,
    room_dimensions: [],
    balcony_area: null,
    terrace_area: null,
    garden_area: 9500,
    pool_size: null,
    features: ['park_view', 'standard_plot', 'g_plus_1_allowance', 'near_amenities'],
    extracted_text: null,
    summary: 'Standard plot (9,500 sqft) in Harmony Phase 2 with park views. G+1 building allowance. Close to community amenities and retail.',
    extraction_confidence: 0.93,
    processed_at: new Date().toISOString(),
    processing_time_ms: 1900,
    model_used: 'gpt-4-vision',
  },
}

export const demoDocuments: SmartDocument[] = [
  {
    id: 'doc-1',
    user_id: 'demo-user-001',
    collection_id: 'col-2',
    name: 'Garden Villa Floor Plan',
    description: 'Ground floor and first floor layout',
    document_type: 'floor_plan',
    file_url: '/demo/palm-villa-floor.pdf',
    file_name: 'palm-villa-floor.pdf',
    file_size: 2500000,
    file_type: 'application/pdf',
    thumbnail_url: null,
    latitude: 25.1124,
    longitude: 55.1390,
    address: 'Frond K, Palm Jumeirah',
    area_name: 'Palm Jumeirah',
    property_name: 'Garden Villa Type A',
    developer: 'Nakheel',
    project_name: 'Palm Jumeirah',
    analysis_status: 'completed',
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    analysis: demoAnalysis['doc-1'],
  },
  {
    id: 'doc-2',
    user_id: 'demo-user-001',
    collection_id: 'col-2',
    name: 'Signature Villa Specs',
    description: 'Technical specifications and measurements',
    document_type: 'spec_sheet',
    file_url: '/demo/signature-specs.pdf',
    file_name: 'signature-specs.pdf',
    file_size: 1800000,
    file_type: 'application/pdf',
    thumbnail_url: null,
    latitude: 25.1150,
    longitude: 55.1420,
    address: 'Frond M, Palm Jumeirah',
    area_name: 'Palm Jumeirah',
    property_name: 'Signature Villa',
    developer: 'Nakheel',
    project_name: 'Palm Jumeirah',
    analysis_status: 'completed',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    analysis: demoAnalysis['doc-2'],
  },
  {
    id: 'doc-3',
    user_id: 'demo-user-001',
    collection_id: 'col-3',
    name: 'Burj Vista 2BR Layout',
    description: 'Two bedroom apartment floor plan',
    document_type: 'floor_plan',
    file_url: '/demo/burj-vista-2br.pdf',
    file_name: 'burj-vista-2br.pdf',
    file_size: 1500000,
    file_type: 'application/pdf',
    thumbnail_url: null,
    latitude: 25.1972,
    longitude: 55.2744,
    address: 'Downtown Dubai',
    area_name: 'Downtown Dubai',
    property_name: 'Burj Vista Tower 1',
    developer: 'Emaar',
    project_name: 'Downtown Dubai',
    analysis_status: 'completed',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    analysis: demoAnalysis['doc-3'],
  },
  {
    id: 'doc-4',
    user_id: 'demo-user-001',
    collection_id: 'col-4',
    name: 'Tilal Al Ghaf Plot A12',
    description: 'Corner plot with lagoon view',
    document_type: 'plot_map',
    file_url: '/demo/tag-plot-a12.pdf',
    file_name: 'tag-plot-a12.pdf',
    file_size: 3200000,
    file_type: 'application/pdf',
    thumbnail_url: null,
    latitude: 25.0156,
    longitude: 55.2048,
    address: 'Harmony Phase 2',
    area_name: 'Tilal Al Ghaf',
    property_name: 'Plot A12',
    developer: 'Majid Al Futtaim',
    project_name: 'Tilal Al Ghaf',
    analysis_status: 'completed',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    analysis: demoAnalysis['doc-4'],
  },
  {
    id: 'doc-5',
    user_id: 'demo-user-001',
    collection_id: 'col-4',
    name: 'Tilal Al Ghaf Plot B7',
    description: 'Standard plot with park view',
    document_type: 'plot_map',
    file_url: '/demo/tag-plot-b7.pdf',
    file_name: 'tag-plot-b7.pdf',
    file_size: 2800000,
    file_type: 'application/pdf',
    thumbnail_url: null,
    latitude: 25.0162,
    longitude: 55.2055,
    address: 'Harmony Phase 2',
    area_name: 'Tilal Al Ghaf',
    property_name: 'Plot B7',
    developer: 'Majid Al Futtaim',
    project_name: 'Tilal Al Ghaf',
    analysis_status: 'completed',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    analysis: demoAnalysis['doc-5'],
  },
]

export const demoChatMessages: SmartChatMessage[] = [
  {
    id: 'msg-1',
    user_id: 'demo-user-001',
    collection_id: 'col-2',
    role: 'user',
    content: 'What is the size difference between the Garden Villa and Signature Villa?',
    document_ids: ['doc-1', 'doc-2'],
    model_used: null,
    tokens_used: null,
    created_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'msg-2',
    user_id: 'demo-user-001',
    collection_id: 'col-2',
    role: 'assistant',
    content: `Based on the floor plans and specifications:

**Garden Villa:**
- Plot Size: 8,500 sqft
- Built-up Area: 6,200 sqft
- Bedrooms: 5
- Bathrooms: 6

**Signature Villa:**
- Plot Size: 15,000 sqft
- Built-up Area: 12,500 sqft
- Bedrooms: 7
- Bathrooms: 8

**Key Differences:**
- The Signature Villa is almost **twice the size** (6,300 sqft more built-up area)
- Plot is 6,500 sqft larger
- 2 additional bedrooms
- Premium features include private marina, infinity pool, and elevator
- Price point would be significantly higher (typically 3-4x)`,
    document_ids: ['doc-1', 'doc-2'],
    model_used: 'gpt-4',
    tokens_used: 320,
    created_at: new Date(Date.now() - 59 * 60 * 1000).toISOString(),
  },
]

// Suggested questions for the chat interface
export const suggestedQuestions = [
  "What's the total built-up area of my floor plans?",
  "Compare the two plots in my collection",
  "Which property has the most bedrooms?",
  "Show me properties with swimming pools",
  "What features does the Signature Villa have?",
  "Calculate the price per sqft for Palm Jumeirah",
]

// Feature labels for display
export const featureLabels: Record<string, string> = {
  private_pool: 'Private Pool',
  infinity_pool: 'Infinity Pool',
  maid_room: "Maid's Room",
  driver_room: "Driver's Room",
  home_cinema: 'Home Cinema',
  gym: 'Private Gym',
  sauna: 'Sauna',
  beach_access: 'Beach Access',
  private_marina: 'Private Marina',
  elevator: 'Private Elevator',
  wine_cellar: 'Wine Cellar',
  spa: 'Spa',
  staff_quarters: 'Staff Quarters',
  burj_khalifa_view: 'Burj Khalifa View',
  balcony: 'Balcony',
  built_in_wardrobes: 'Built-in Wardrobes',
  premium_finishes: 'Premium Finishes',
  corner_plot: 'Corner Plot',
  lagoon_view: 'Lagoon View',
  park_view: 'Park View',
  premium_location: 'Premium Location',
  standard_plot: 'Standard Plot',
  g_plus_1_allowance: 'G+1 Building Allowance',
  g_plus_2_allowance: 'G+2 Building Allowance',
  near_amenities: 'Near Amenities',
}
